use_frameworks!

target 'PopcornNotify_Example' do
  pod 'PopcornNotify', :path => '../'

  target 'PopcornNotify_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
